HouseholdManager/HouseholdManager.Web/Areas/Household/Models/ExpenseViewModel.cs
using AutoMapper;
using HouseholdManager.Common.Contracts;
using HouseholdManager.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace HouseholdManager.Web.Areas.Household.Models
{
    public class ExpenseViewModel: IMapFrom<Expense>, IHaveCustomMappings
    {
        public Guid Id { get; set; }

        [Required]
        [StringLength(30, ErrorMessage = "The {0} must be between {2} and 30 characters long.", MinimumLength = 2)]
        public string Name { get; set; }

        public string Category { get; set; }

        [Display(Name = "Assigned user")]
        public string AssignedUser { get; set; }

        [Display(Name = "Created by")]
        public string CreatedBy { get; set; }

        [Display(Name = "Due date")]
        public DateTime DueDate { get; set; }

        [Required(ErrorMessage = " Expected cost is required.")]
        [Range(0, double.MaxValue, ErrorMessage = "The expected cost cannot be a negative number.")]
        [Display(Name = "Expected cost")]
        public decimal ExpectedCost { get; set; }

        [StringLength(200, ErrorMessage = "The {0} must be maximum 200 characters long.")]
        public string Comment { get; set; }

        [Range(0, double.MaxValue, ErrorMessage = "The cost cannot be a negative number.")]
        [Display(Name = "Paid cost")]
        public decimal? Cost { get; set; }

        [Display(Name = "Paid on date")]
        public DateTime? PaidOnDate { get; set; }

        [Display(Name = "Created on")]
        public DateTime CreatedOn { get; set; }

        [Display(Name = "Is paid")]
        public bool IsPaid { get; set; }

        [Display(Name = "Paid by")]
        public string PaidBy { get; set; }

        public IList<SelectListItem> CategoriesList { get; set; }

        public IList<SelectListItem> Users { get; set; }

        public void CreateMappings(IMapperConfigurationExpression configuration)
        {
            configuration.CreateMap<Expense, ExpenseViewModel>()
                .ForMember(d => d.Category, opt => opt.MapFrom(s => s.ExpenseCategory.Name))
                .ForMember(d => d.AssignedUser, opt => opt.MapFrom(s => s.AssignedUser.FirstName + " " + s.AssignedUser.LastName))
                .ForMember(d => d.CreatedBy, opt => opt.MapFrom(s => s.CreatedBy.FirstName + " " + s.CreatedBy.LastName))
                .ForMember(d => d.PaidBy, opt => opt.MapFrom(s => s.PaidBy.FirstName + " " + s.PaidBy.LastName));
        }
    }
}

HouseholdManager/HouseholdManager.Web/Areas/Household/Controllers/ExpenseController.cs
using HouseholdManager.Common.Constants;
using HouseholdManager.Common.Contracts;
using HouseholdManager.Logic.Contracts;
using HouseholdManager.Web.Areas.Household.Models;
using HouseholdManager.Web.Controllers;
using HouseholdManager.Web.WebHelpers.Contracts;
using System;
using System.Collections.Generic;
using System.Web.Mvc;

namespace HouseholdManager.Web.Areas.Household.Controllers
{
    [Authorize]
    public class ExpenseController : BaseController
    {
        private readonly IHouseholdService householdService;
        private readonly IExpenseService expenseService;

        public ExpenseController(IExpenseService expenseService, IMapingService mappingService, IHouseholdService householdService, IWebHelper webHelper)
            : base(mappingService, webHelper)
        {
            if (expenseService == null)
            {
                throw new ArgumentNullException(string.Format(ExceptionConstants.ArgumentCannotBeNull, "expenseService"));
            }

            if (householdService == null)
            {
                throw new ArgumentNullException(string.Format(ExceptionConstants.ArgumentCannotBeNull, "householdService"));
            }

            this.expenseService = expenseService;
            this.householdService = householdService;
        }

        [HttpGet]
        public ActionResult Index(Guid id)
        {
            var expense = this.expenseService.GetExpense(id);
            if (expense.HouseholdId != this.webHelper.GetHouseholdIdFromCookie())
            {
                return Redirect("/Error/Unauthorized");
            }

            var mapped = this.mappingService.Map<ExpenseViewModel>(expense);

            return View(mapped);
        }


        [HttpGet]
        public ActionResult Create()
        {
            var modelCategories = this.PrepareModelCategories();
            var model = new ExpenseViewModel() { CategoriesList = modelCategories };
            model.Users = this.PrepareModelUsers();

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Exclude = "Cost, PaidOnDate, CreatedOn, IsPaid, PaidBy")] ExpenseViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return Redirect("/Error/BadRequest");
            }

            var householdid = this.webHelper.GetHouseholdIdFromCookie();
            this.expenseService.CreateExpense(this.webHelper.GetUserId(), model.Name, Guid.Parse(model.Category), householdid, model.ExpectedCost, model.DueDate, model.Comment, model.AssignedUser);

            return RedirectToAction("Index", "Expenses", new { name = this.webHelper.GetHouseholdNameFromCookie() });
        }

        [HttpGet]
        public ActionResult Edit(string id)
        {
            var expense = this.expenseService.GetExpense(Guid.Parse(id));
            if (expense.HouseholdId != this.webHelper.GetHouseholdIdFromCookie())
            {
                return Redirect("/Error/Unauthorized");
            }

            var model = this.mappingService.Map<ExpenseViewModel>(expense);
            model.CategoriesList = this.PrepareModelCategories();
            model.Users = this.PrepareModelUsers();
            model.AssignedUser = expense.AssignedUserId;
            model.Category = expense.CategoryId.ToString();

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id, Name, Category, AssignedUser, DueDate, ExpectedCost")] ExpenseViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return Redirect("/Error/BadRequest");
            }

            this.expenseService.UpdateExpense(model.Id, model.Name, Guid.Parse(model.Category), model.ExpectedCost, model.DueDate, model.AssignedUser);
            return RedirectToAction("Index", new { id = model.Id });
        }

        [HttpPost]
        public ActionResult Delete([Bind(Include = "Id")] ExpenseViewModel model)
        {
            this.expenseService.DeleteExpense(model.Id, true);
            return RedirectToAction("Index", new { id = model.Id });
        }

        private IList<SelectListItem> PrepareModelCategories()
        {
            var expenseCateogries = this.expenseService.GetExpenseCategories();
            var modelCategories = new List<SelectListItem>();
            foreach (var category in expenseCateogries)
            {
                modelCategories.Add(new SelectListItem() { Value = category.Id.ToString(), Text = category.Name });
            }

            return modelCategories;
        }

        private IList<SelectListItem> PrepareModelUsers()
        {
            var householdid = this.webHelper.GetHouseholdIdFromCookie();
            var users = this.householdService.GetHouseholdUsers(householdid);
            var modelUsers = new List<SelectListItem>();
            foreach (var user in users)
            {
                modelUsers.Add(new SelectListItem() { Value = user.Id, Text = user.FirstName + " " + user.LastName });
            }

            return modelUsers;
        }
    }
}

HouseholdManager/HouseholdManager.Web/Areas/Household/Views/Expense/Create.cshtml
@model HouseholdManager.Web.Areas.Household.Models.ExpenseViewModel
@section styles {
    @Styles.Render("~/Content/kendo/css")
}
@section kendoScripts {
    @Scripts.Render("~/bundles/kendo")
}

<div class="row">
    <div class="col-md-8 col-md-offset-4 col-sm-6 col-sm-offset-4 col-xs-offset-2">
        <h2 class="header-page">Add expense</h2>

        @using (Html.BeginForm("Create", "Expense", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
            {
            @Html.AntiForgeryToken()

            <div class="form-group">
                @Html.LabelFor(m => m.Name, new { @class = "col-md-2 control-label" })
                @Html.ValidationMessageFor(m => m.Name, "", new { @class = "text-danger" })
                <div class="col-md-10">
                    @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(m => m.Category, new { @class = "col-md-2 control-label" })
                @Html.ValidationMessageFor(m => m.Category, "", new { @class = "text-danger" })
                <div class="col-md-10">
                    @Html.DropDownListFor(m => m.Category, Model.CategoriesList, new { @class = "form-control" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(m => m.ExpectedCost, new { @class = "col-md-2 control-label" })
                @Html.ValidationMessageFor(m => m.ExpectedCost, "", new { @class = "text-danger" })
                <div class="col-md-10">
                    @Html.TextBoxFor(m => m.ExpectedCost, new { @class = "form-control" })
                </div>
            </div>

                <div class="form-group">
                    @Html.LabelFor(m => m.DueDate, new { @class = "col-md-2 control-label" })
                    @Html.ValidationMessageFor(m => m.DueDate, "", new { @class = "text-danger" })
                    <div class="col-md-10">
                        @(Html.Kendo().DatePickerFor(m => m.DueDate)
                        .Value(DateTime.Now)
                        .Format("yyyy/MM/dd")
                        )
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(m => m.AssignedUser, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.DropDownListFor(m => m.AssignedUser, Model.Users, "Choose user", new { @class = "form-control" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(m => m.Comment, new { @class = "col-md-2 control-label" })
                    @Html.ValidationMessageFor(m => m.Comment, "", new { @class = "text-danger" })
                    <div class="col-md-10">
                        @Html.TextAreaFor(m => m.Comment, new { @class = "form-control" })
                    </div>
                </div>


                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="SUBMIT" class="btn btn-default" />
                    </div>
                </div>
        }
    </div>
</div>

@section scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

HouseholdManager/HouseholdManager.Web/Areas/Household/Views/Expense/Edit.cshtml
@using HouseholdManager.Common.Constants
@model HouseholdManager.Web.Areas.Household.Models.ExpenseViewModel
@{
    var householdName = this.Request.Cookies[CommonConstants.CurrentHousehold]?[CommonConstants.CurrentHouseholdName];
}

@section styles {
    @Styles.Render("~/Content/kendo/css")
}

@section kendoScripts {
    @Scripts.Render("~/bundles/kendo")
}

<h2 class="header-page text-center">@householdName</h2>
@Html.EditorForModel(Model)

@section scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

HouseholdManager/HouseholdManager.Web/Areas/Household/Views/Expense/Index.cshtml
@using HouseholdManager.Common.Constants

@model HouseholdManager.Web.Areas.Household.Models.ExpenseViewModel
@{ 
    var householdName = this.Request.Cookies[CommonConstants.CurrentHousehold]?[CommonConstants.CurrentHouseholdName];
}
<h1 class="color-blue text-center">@householdName</h1>
@Html.DisplayForModel(Model)

@section scripts {
    @Scripts.Render("~/bundles/jqueryval")
}